# -*- coding: utf-8 -*-
import time
import threading
# Form implementation generated from reading ui file 'Robot_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import socket
import sys

HEADER = 64
PORT = 12347
FORMAT = "utf-8"
DISCONNECT_MESSAGE = "!DISCONNECT"
SERVER = "localhost"
# SERVER = "192.168.1.10"
ADDR = (SERVER, PORT)
RESPOND = "ready_to_transfer"

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(ADDR)


def popup(title, text):
    msg = QMessageBox()
    msg.setIcon(QMessageBox.Information)

    msg.setText(text)
    msg.setWindowTitle(title)
    retval = msg.exec_()
    print(msg.text())


def reconnect():
    global client
    print("attempt to reconnect")
    client.close()
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client.connect(ADDR)
    print("attempted...")


class Worker(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(str)

    def run(self):
        """Long-running task."""
        recv = ""
        while True:
            try:
                recv = client.recv(64).decode("utf-8")
                recv = recv.strip("z")
                if recv != "z" and len(recv) > 0:
                    print(f"received: {recv}")
            except:
                print("failed")
            if len(recv) > 1:
                self.progress.emit(recv)
            if recv == "break":
                print("break")
                break
            time.sleep(0.1)
        self.finished.emit()


class WorkerThread(QThread):
    progress_tmr = pyqtSignal(float)
    stop = 0
    cntr = 0.0
    def run(self):
        self.stop = 0
        while not self.stop:
            self.cntr += 0.01
            self.progress_tmr.emit(self.cntr)
            time.sleep(0.1)

    def stop_cnt(self):
        self.stop = 1


class Ui_MainWindow(object):
    active = True
    cycles = 0
    PAUSE = 0
    error_samples = {"no_parts_present": ("Please load more parts and hit start button.", "Empty table"),
                     "water_level_is_low": ("Please add more water into basin", "Low water level"),
                     "out_feed_table_is_full": ("Please remove parts from out feed table", "Out feed table is full")}

    def __init__(self):
        self.timer_thread_list = []
        self.LRL_thread_id = None
        self.LRR_thread_id = None
        self.SRL_thread_id = None
        self.SRR_thread_id = None
        self.cycle_timer_SR = None
        self.millsec_sr = 0.0
        self.millsec_br = 0.0
        self.robot_side = ""
        self.cycle_timer_BR = None
        self.timer = None
        self.side = ""
        self.lr_r_part_cnt = 0
        self.lr_l_part_cnt = 0
        self.sr_r_part_cnt = 0
        self.sr_l_part_cnt = 0
        self.SR_Offset = 0
        self.BR_Offset = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 740)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "centralwidget.setStyleSheet(\"background-image: url(\'C:/Users/66ase/Desktop/UI for \"\n"
            "                                    \"deburr/logo.png\'); background-position: center;\")")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PrB_grWheel2LR = QtWidgets.QProgressBar(self.groupBox_8)
        self.PrB_grWheel2LR.setMinimum(0)
        self.PrB_grWheel2LR.setMaximum(100)
        self.PrB_grWheel2LR.setProperty("value", 100)
        self.PrB_grWheel2LR.setAlignment(QtCore.Qt.AlignCenter)
        self.PrB_grWheel2LR.setTextVisible(True)
        self.PrB_grWheel2LR.setOrientation(QtCore.Qt.Horizontal)
        self.PrB_grWheel2LR.setInvertedAppearance(True)
        self.PrB_grWheel2LR.setObjectName("PrB_grWheel2LR")
        self.gridLayout_3.addWidget(self.PrB_grWheel2LR, 6, 0, 1, 6)
        self.largeRobLPart8 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart8.setFont(font)
        self.largeRobLPart8.setObjectName("largeRobLPart8")
        self.gridLayout_3.addWidget(self.largeRobLPart8, 11, 2, 1, 1)
        self.largeRobLPart6 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart6.setFont(font)
        self.largeRobLPart6.setObjectName("largeRobLPart6")
        self.gridLayout_3.addWidget(self.largeRobLPart6, 11, 0, 1, 1)
        self.PrB_grWheel1LR = QtWidgets.QProgressBar(self.groupBox_8)
        self.PrB_grWheel1LR.setMinimum(0)
        self.PrB_grWheel1LR.setMaximum(100)
        self.PrB_grWheel1LR.setProperty("value", 100)
        self.PrB_grWheel1LR.setAlignment(QtCore.Qt.AlignCenter)
        self.PrB_grWheel1LR.setTextVisible(True)
        self.PrB_grWheel1LR.setOrientation(QtCore.Qt.Horizontal)
        self.PrB_grWheel1LR.setInvertedAppearance(True)
        self.PrB_grWheel1LR.setObjectName("PrB_grWheel1LR")
        self.gridLayout_3.addWidget(self.PrB_grWheel1LR, 4, 0, 1, 6)
        self.LR_Active_Stat = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_Active_Stat.setFont(font)
        self.LR_Active_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_Active_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_Active_Stat.setObjectName("LR_Active_Stat")
        self.gridLayout_3.addWidget(self.LR_Active_Stat, 1, 0, 1, 2)
        self.largeRobLPart3 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart3.setFont(font)
        self.largeRobLPart3.setObjectName("largeRobLPart3")
        self.gridLayout_3.addWidget(self.largeRobLPart3, 10, 0, 1, 1)
        self.largeRobRPart4 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart4.setFont(font)
        self.largeRobRPart4.setObjectName("largeRobRPart4")
        self.gridLayout_3.addWidget(self.largeRobRPart4, 10, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_34.setFont(font)
        self.label_34.setScaledContents(False)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 0, 1, 6)
        self.largeRobRPart6 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart6.setFont(font)
        self.largeRobRPart6.setObjectName("largeRobRPart6")
        self.gridLayout_3.addWidget(self.largeRobRPart6, 11, 3, 1, 1)
        self.largeRobRPart0 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart0.setFont(font)
        self.largeRobRPart0.setObjectName("largeRobRPart0")
        self.gridLayout_3.addWidget(self.largeRobRPart0, 9, 3, 1, 1)
        self.largeRobLPart1 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart1.setFont(font)
        self.largeRobLPart1.setObjectName("largeRobLPart1")
        self.gridLayout_3.addWidget(self.largeRobLPart1, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 12, 0, 1, 6)
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 5, 0, 1, 3)
        self.largeRobRPart5 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart5.setFont(font)
        self.largeRobRPart5.setObjectName("largeRobRPart5")
        self.gridLayout_3.addWidget(self.largeRobRPart5, 10, 5, 1, 1)
        self.LR_Pause_Stat = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_Pause_Stat.setFont(font)
        self.LR_Pause_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_Pause_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_Pause_Stat.setObjectName("LR_Pause_Stat")
        self.gridLayout_3.addWidget(self.LR_Pause_Stat, 1, 2, 1, 2)
        self.LR_Fault_Stat = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_Fault_Stat.setFont(font)
        self.LR_Fault_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_Fault_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_Fault_Stat.setObjectName("LR_Fault_Stat")
        self.gridLayout_3.addWidget(self.LR_Fault_Stat, 1, 4, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 7, 0, 1, 6)
        self.largeRobLPart2 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart2.setFont(font)
        self.largeRobLPart2.setObjectName("largeRobLPart2")
        self.gridLayout_3.addWidget(self.largeRobLPart2, 9, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 3)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 6)
        self.largeRobRPart8 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart8.setFont(font)
        self.largeRobRPart8.setObjectName("largeRobRPart8")
        self.gridLayout_3.addWidget(self.largeRobRPart8, 11, 5, 1, 1)
        self.largeRobRPart7 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart7.setFont(font)
        self.largeRobRPart7.setObjectName("largeRobRPart7")
        self.gridLayout_3.addWidget(self.largeRobRPart7, 11, 4, 1, 1)
        self.largeRobLPart5 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart5.setFont(font)
        self.largeRobLPart5.setObjectName("largeRobLPart5")
        self.gridLayout_3.addWidget(self.largeRobLPart5, 10, 2, 1, 1)
        self.largeRobRPart2 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart2.setFont(font)
        self.largeRobRPart2.setObjectName("largeRobRPart2")
        self.gridLayout_3.addWidget(self.largeRobRPart2, 9, 5, 1, 1)
        self.largeRobLPart7 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart7.setFont(font)
        self.largeRobLPart7.setObjectName("largeRobLPart7")
        self.gridLayout_3.addWidget(self.largeRobLPart7, 11, 1, 1, 1)
        self.largeRobRPart1 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart1.setFont(font)
        self.largeRobRPart1.setObjectName("largeRobRPart1")
        self.gridLayout_3.addWidget(self.largeRobRPart1, 9, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 5, 3, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 3, 1, 3)
        self.largeRobLPart0 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart0.setFont(font)
        self.largeRobLPart0.setObjectName("largeRobLPart0")
        self.gridLayout_3.addWidget(self.largeRobLPart0, 9, 0, 1, 1)
        self.largeRobRPart3 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobRPart3.setFont(font)
        self.largeRobRPart3.setObjectName("largeRobRPart3")
        self.gridLayout_3.addWidget(self.largeRobRPart3, 10, 3, 1, 1)
        self.largeRobLPart4 = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeRobLPart4.setFont(font)
        self.largeRobLPart4.setObjectName("largeRobLPart4")
        self.gridLayout_3.addWidget(self.largeRobLPart4, 10, 1, 1, 1)
        self.BR_Offset_Val = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_Offset_Val.setFont(font)
        self.BR_Offset_Val.setFrameShape(QtWidgets.QFrame.Box)
        self.BR_Offset_Val.setLineWidth(2)
        self.BR_Offset_Val.setText("0")
        self.BR_Offset_Val.setAlignment(QtCore.Qt.AlignCenter)
        self.BR_Offset_Val.setObjectName("label")
        self.gridLayout_3.addWidget(self.BR_Offset_Val, 13, 2, 1, 2)
        self.PB_BR_Off_UP = QtWidgets.QPushButton(self.groupBox_8)
        self.PB_BR_Off_UP.setObjectName("PB_BR_Off_UP")
        self.gridLayout_3.addWidget(self.PB_BR_Off_UP, 13, 0, 1, 2)
        self.PB_BR_Off_DOWN = QtWidgets.QPushButton(self.groupBox_8)
        self.PB_BR_Off_DOWN.setObjectName("PB_BR_Off_DOWN")
        self.gridLayout_3.addWidget(self.PB_BR_Off_DOWN, 13, 4, 1, 2)
        self.gridLayout.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setStyleSheet(
            "MainWindow.setStyleSheet(\"background-image: url(\'C:\\Users\\66ase\\Desktop\\UI for deburr\\logo.png) \'); background-repeat: no-repeat; background-position: center;\")")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LR_right_part_ctr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_right_part_ctr.setFont(font)
        self.LR_right_part_ctr.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_right_part_ctr.setText("")
        self.LR_right_part_ctr.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_right_part_ctr.setObjectName("LR_right_part_ctr")
        self.gridLayout_2.addWidget(self.LR_right_part_ctr, 8, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 1, 1, 2)
        self.SR_right_part_ctr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_right_part_ctr.setFont(font)
        self.SR_right_part_ctr.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_right_part_ctr.setText("")
        self.SR_right_part_ctr.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_right_part_ctr.setObjectName("SR_right_part_ctr")
        self.gridLayout_2.addWidget(self.SR_right_part_ctr, 8, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 2)
        self.RB_Left_only = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RB_Left_only.setFont(font)
        self.RB_Left_only.setObjectName("RB_Left_only")
        self.gridLayout_2.addWidget(self.RB_Left_only, 9, 2, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 7, 0, 1, 1)
        self.SR_left_part_tmr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_left_part_tmr.setFont(font)
        self.SR_left_part_tmr.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_left_part_tmr.setText("")
        self.SR_left_part_tmr.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_left_part_tmr.setObjectName("SR_left_part_tmr")
        self.gridLayout_2.addWidget(self.SR_left_part_tmr, 3, 3, 1, 1)
        self.RB_Intermittent = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RB_Intermittent.setFont(font)
        self.RB_Intermittent.setObjectName("RB_Intermittent")
        self.gridLayout_2.addWidget(self.RB_Intermittent, 10, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 8, 0, 1, 1)
        self.LR_right_part_tmr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_right_part_tmr.setFont(font)
        self.LR_right_part_tmr.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_right_part_tmr.setText("")
        self.LR_right_part_tmr.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_right_part_tmr.setObjectName("LR_right_part_tmr")
        self.gridLayout_2.addWidget(self.LR_right_part_tmr, 4, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 3, 1, 1)
        self.LR_left_part_tmr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_left_part_tmr.setFont(font)
        self.LR_left_part_tmr.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_left_part_tmr.setText("")
        self.LR_left_part_tmr.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_left_part_tmr.setObjectName("LR_left_part_tmr")
        self.gridLayout_2.addWidget(self.LR_left_part_tmr, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 1)
        self.PB_Pause_seq = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PB_Pause_seq.setFont(font)
        self.PB_Pause_seq.setDefault(False)
        self.PB_Pause_seq.setFlat(False)
        self.PB_Pause_seq.setObjectName("PB_Pause_seq")
        self.gridLayout_2.addWidget(self.PB_Pause_seq, 11, 0, 1, 2)
        self.SR_left_part_ctr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_left_part_ctr.setFont(font)
        self.SR_left_part_ctr.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_left_part_ctr.setText("")
        self.SR_left_part_ctr.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_left_part_ctr.setObjectName("SR_left_part_ctr")
        self.gridLayout_2.addWidget(self.SR_left_part_ctr, 7, 3, 1, 1)
        self.PB_Resume_seq = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PB_Resume_seq.setFont(font)
        self.PB_Resume_seq.setDefault(False)
        self.PB_Resume_seq.setFlat(False)
        self.PB_Resume_seq.setObjectName("PB_Resume_seq")
        self.gridLayout_2.addWidget(self.PB_Resume_seq, 11, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.RB_Right_only = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RB_Right_only.setFont(font)
        self.RB_Right_only.setObjectName("RB_Right_only")
        self.gridLayout_2.addWidget(self.RB_Right_only, 10, 2, 1, 2)
        self.SR_right_part_tmr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_right_part_tmr.setFont(font)
        self.SR_right_part_tmr.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_right_part_tmr.setText("")
        self.SR_right_part_tmr.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_right_part_tmr.setObjectName("SR_right_part_tmr")
        self.gridLayout_2.addWidget(self.SR_right_part_tmr, 4, 3, 1, 1)
        self.LR_left_part_ctr = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LR_left_part_ctr.setFont(font)
        self.LR_left_part_ctr.setFrameShape(QtWidgets.QFrame.Panel)
        self.LR_left_part_ctr.setText("")
        self.LR_left_part_ctr.setAlignment(QtCore.Qt.AlignCenter)
        self.LR_left_part_ctr.setObjectName("LR_left_part_ctr")
        self.gridLayout_2.addWidget(self.LR_left_part_ctr, 7, 1, 1, 2)
        self.RB_One_side = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RB_One_side.setFont(font)
        self.RB_One_side.setAcceptDrops(False)
        self.RB_One_side.setAutoFillBackground(False)
        self.RB_One_side.setIconSize(QtCore.QSize(30, 30))
        self.RB_One_side.setChecked(True)
        self.RB_One_side.setObjectName("RB_One_side")
        self.gridLayout_2.addWidget(self.RB_One_side, 9, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setWhatsThis("")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PrB_grWheelSR = QtWidgets.QProgressBar(self.groupBox_7)
        self.PrB_grWheelSR.setMinimum(0)
        self.PrB_grWheelSR.setMaximum(100)
        self.PrB_grWheelSR.setProperty("value", 100)
        self.PrB_grWheelSR.setAlignment(QtCore.Qt.AlignCenter)
        self.PrB_grWheelSR.setTextVisible(True)
        self.PrB_grWheelSR.setOrientation(QtCore.Qt.Horizontal)
        self.PrB_grWheelSR.setInvertedAppearance(True)
        self.PrB_grWheelSR.setObjectName("PrB_grWheelSR")
        self.gridLayout_4.addWidget(self.PrB_grWheelSR, 4, 0, 1, 6)
        self.SR_Act_Stat = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_Act_Stat.setFont(font)
        self.SR_Act_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_Act_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_Act_Stat.setObjectName("SR_Act_Stat")
        self.gridLayout_4.addWidget(self.SR_Act_Stat, 1, 0, 1, 2)
        self.smallRobLPart7 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart7.setFont(font)
        self.smallRobLPart7.setObjectName("smallRobLPart7")
        self.gridLayout_4.addWidget(self.smallRobLPart7, 9, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 5, 0, 1, 1)
        self.smallRobRPart6 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart6.setFont(font)
        self.smallRobRPart6.setObjectName("smallRobRPart6")
        self.gridLayout_4.addWidget(self.smallRobRPart6, 9, 3, 1, 1)
        self.smallRobLPart8 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart8.setFont(font)
        self.smallRobLPart8.setObjectName("smallRobLPart8")
        self.gridLayout_4.addWidget(self.smallRobLPart8, 9, 2, 1, 1)
        self.smallRobLPart0 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart0.setFont(font)
        self.smallRobLPart0.setObjectName("smallRobLPart0")
        self.gridLayout_4.addWidget(self.smallRobLPart0, 7, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_30.setFont(font)
        self.label_30.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 6)
        self.label_32 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 3, 3, 1, 3)
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 3, 0, 1, 3)
        self.smallRobRPart1 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart1.setFont(font)
        self.smallRobRPart1.setObjectName("smallRobRPart1")
        self.gridLayout_4.addWidget(self.smallRobRPart1, 7, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 6)
        self.smallRobLPart6 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart6.setFont(font)
        self.smallRobLPart6.setObjectName("smallRobLPart6")
        self.gridLayout_4.addWidget(self.smallRobLPart6, 9, 0, 1, 1)
        self.smallRobLPart2 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart2.setFont(font)
        self.smallRobLPart2.setObjectName("smallRobLPart2")
        self.gridLayout_4.addWidget(self.smallRobLPart2, 7, 2, 1, 1)
        self.smallRobRPart7 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart7.setFont(font)
        self.smallRobRPart7.setObjectName("smallRobRPart7")
        self.gridLayout_4.addWidget(self.smallRobRPart7, 9, 4, 1, 1)
        self.smallRobRPart2 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart2.setFont(font)
        self.smallRobRPart2.setObjectName("smallRobRPart2")
        self.gridLayout_4.addWidget(self.smallRobRPart2, 7, 5, 1, 1)
        self.smallRobRPart3 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart3.setFont(font)
        self.smallRobRPart3.setObjectName("smallRobRPart3")
        self.gridLayout_4.addWidget(self.smallRobRPart3, 8, 3, 1, 1)
        self.SR_Pause_Stat = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_Pause_Stat.setFont(font)
        self.SR_Pause_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_Pause_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_Pause_Stat.setObjectName("SR_Pause_Stat")
        self.gridLayout_4.addWidget(self.SR_Pause_Stat, 1, 2, 1, 2)
        self.smallRobLPart4 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart4.setFont(font)
        self.smallRobLPart4.setObjectName("smallRobLPart4")
        self.gridLayout_4.addWidget(self.smallRobLPart4, 8, 1, 1, 1)
        self.smallRobRPart4 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart4.setFont(font)
        self.smallRobRPart4.setObjectName("smallRobRPart4")
        self.gridLayout_4.addWidget(self.smallRobRPart4, 8, 4, 1, 1)
        self.smallRobRPart0 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart0.setFont(font)
        self.smallRobRPart0.setObjectName("smallRobRPart0")
        self.gridLayout_4.addWidget(self.smallRobRPart0, 7, 3, 1, 1)
        self.smallRobLPart1 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart1.setFont(font)
        self.smallRobLPart1.setObjectName("smallRobLPart1")
        self.gridLayout_4.addWidget(self.smallRobLPart1, 7, 1, 1, 1)
        self.smallRobLPart3 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart3.setFont(font)
        self.smallRobLPart3.setObjectName("smallRobLPart3")
        self.gridLayout_4.addWidget(self.smallRobLPart3, 8, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 6, 0, 1, 6)
        self.SR_Fault_Stat = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SR_Fault_Stat.setFont(font)
        self.SR_Fault_Stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.SR_Fault_Stat.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_Fault_Stat.setObjectName("SR_Fault_Stat")
        self.gridLayout_4.addWidget(self.SR_Fault_Stat, 1, 4, 1, 2)
        self.smallRobRPart5 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart5.setFont(font)
        self.smallRobRPart5.setObjectName("smallRobRPart5")
        self.gridLayout_4.addWidget(self.smallRobRPart5, 8, 5, 1, 1)
        self.smallRobRPart8 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobRPart8.setFont(font)
        self.smallRobRPart8.setObjectName("smallRobRPart8")
        self.gridLayout_4.addWidget(self.smallRobRPart8, 9, 5, 1, 1)
        self.smallRobLPart5 = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallRobLPart5.setFont(font)
        self.smallRobLPart5.setObjectName("smallRobLPart5")
        self.gridLayout_4.addWidget(self.smallRobLPart5, 8, 2, 1, 1)
        self.SR_Offset_Val = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SR_Offset_Val.setFont(font)
        self.SR_Offset_Val.setFrameShape(QtWidgets.QFrame.Box)
        self.SR_Offset_Val.setLineWidth(2)
        self.SR_Offset_Val.setText("0")
        self.SR_Offset_Val.setAlignment(QtCore.Qt.AlignCenter)
        self.SR_Offset_Val.setObjectName("SR_Offset_Val")
        self.gridLayout_4.addWidget(self.SR_Offset_Val, 13, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 12, 0, 1, 6)
        self.PB_SR_Off_UP = QtWidgets.QPushButton(self.groupBox_7)
        self.PB_SR_Off_UP.setObjectName("PB_SR_Off_UP")
        self.gridLayout_4.addWidget(self.PB_SR_Off_UP, 13, 0, 1, 2)
        self.PB_SR_Off_DOWN = QtWidgets.QPushButton(self.groupBox_7)
        self.PB_SR_Off_DOWN.setObjectName("PB_SR_Off_DOWN")
        self.gridLayout_4.addWidget(self.PB_SR_Off_DOWN, 13, 4, 1, 2)
        self.gridLayout.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.PB_Trig_Cam = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PB_Trig_Cam.setFont(font)
        self.PB_Trig_Cam.setObjectName("PB_Trig_Cam")
        self.gridLayout.addWidget(self.PB_Trig_Cam, 1, 2, 1, 1)
        self.PB_Reset_SR_Wheel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PB_Reset_SR_Wheel.setFont(font)
        self.PB_Reset_SR_Wheel.setObjectName("PB_Reset_SR_Wheel")
        self.gridLayout.addWidget(self.PB_Reset_SR_Wheel, 1, 0, 1, 1)
        self.PB_Reset_LR_Wheel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PB_Reset_LR_Wheel.setFont(font)
        self.PB_Reset_LR_Wheel.setDefault(False)
        self.PB_Reset_LR_Wheel.setFlat(False)
        self.PB_Reset_LR_Wheel.setObjectName("PB_Reset_LR_Wheel")
        self.gridLayout.addWidget(self.PB_Reset_LR_Wheel, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.check_box_sr_list = [self.smallRobLPart0, self.smallRobLPart1, self.smallRobLPart2, self.smallRobLPart3,
                                  self.smallRobLPart4, self.smallRobLPart5, self.smallRobLPart6, self.smallRobLPart7,
                                  self.smallRobLPart8, self.smallRobRPart0, self.smallRobRPart1, self.smallRobRPart2,
                                  self.smallRobRPart3, self.smallRobRPart4, self.smallRobRPart5, self.smallRobRPart6,
                                  self.smallRobRPart7, self.smallRobRPart8]
        self.check_box_lr_list = [self.largeRobLPart0, self.largeRobLPart1, self.largeRobLPart2, self.largeRobLPart3,
                                  self.largeRobLPart4, self.largeRobLPart5, self.largeRobLPart6, self.largeRobLPart7,
                                  self.largeRobLPart8, self.largeRobRPart0, self.largeRobRPart1, self.largeRobRPart2,
                                  self.largeRobRPart3, self.largeRobRPart4, self.largeRobRPart5, self.largeRobRPart6,
                                  self.largeRobRPart7, self.largeRobRPart8]

        self.PB_Trig_Cam.clicked.connect(self.camera_trig_button)
        self.PB_Reset_SR_Wheel.clicked.connect(self.reset_grind_wheel_s)
        self.PB_Reset_LR_Wheel.clicked.connect(self.reset_grind_wheel_l)
        self.PB_Pause_seq.clicked.connect(self.pause_seq)
        self.PB_Resume_seq.clicked.connect(self.resume_seq)
        # read stored quantity from file
        self.read_from_file()
        # update wheel status bars
        self.display_lr_wheel_stat()
        self.display_sr_wheel_stat()
        # create a timer
        self.timer = QtCore.QTimer()
        # button trigger offset
        self.PB_BR_Off_UP.clicked.connect(lambda: self.extra_offset_BR(dir=1))
        self.PB_BR_Off_DOWN.clicked.connect(lambda: self.extra_offset_BR(dir=-1))
        self.PB_SR_Off_UP.clicked.connect(lambda: self.extra_offset_SR(dir=1))
        self.PB_SR_Off_DOWN.clicked.connect(lambda: self.extra_offset_SR(dir=-1))
        # run polling
        self.runPolling()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.largeRobLPart8.setText(_translate("MainWindow", "9"))
        self.largeRobLPart6.setText(_translate("MainWindow", "7"))
        self.LR_Active_Stat.setText(_translate("MainWindow", "Active"))
        self.largeRobLPart3.setText(_translate("MainWindow", "4"))
        self.largeRobRPart4.setText(_translate("MainWindow", "5"))
        self.label_34.setText(_translate("MainWindow", "Large robot"))
        self.largeRobRPart6.setText(_translate("MainWindow", "7"))
        self.largeRobRPart0.setText(_translate("MainWindow", "1"))
        self.largeRobLPart1.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "Brush offset"))
        self.label_28.setText(_translate("MainWindow", "GOOD"))
        self.largeRobRPart5.setText(_translate("MainWindow", "6"))
        self.LR_Pause_Stat.setText(_translate("MainWindow", "Paused"))
        self.LR_Fault_Stat.setText(_translate("MainWindow", "Faulted"))
        self.label_27.setText(_translate("MainWindow", "Parts presence"))
        self.largeRobLPart2.setText(_translate("MainWindow", "3"))
        self.label_25.setText(_translate("MainWindow", "GOOD"))
        self.label_24.setText(_translate("MainWindow", "Grinding wheel deterioration status"))
        self.largeRobRPart8.setText(_translate("MainWindow", "9"))
        self.largeRobRPart7.setText(_translate("MainWindow", "8"))
        self.largeRobLPart5.setText(_translate("MainWindow", "6"))
        self.largeRobRPart2.setText(_translate("MainWindow", "3"))
        self.largeRobLPart7.setText(_translate("MainWindow", "8"))
        self.largeRobRPart1.setText(_translate("MainWindow", "2"))
        self.label_29.setText(_translate("MainWindow", "REPLACE"))
        self.label_26.setText(_translate("MainWindow", "REPLACE"))
        self.largeRobLPart0.setText(_translate("MainWindow", "1"))
        self.largeRobRPart3.setText(_translate("MainWindow", "4"))
        self.largeRobLPart4.setText(_translate("MainWindow", "5"))
        self.PB_BR_Off_UP.setText(_translate("MainWindow", "Up"))
        self.PB_BR_Off_DOWN.setText(_translate("MainWindow", "Down"))
        self.label_21.setText(_translate("MainWindow", "Big robot"))
        self.label_5.setText(_translate("MainWindow", "Production data"))
        self.label_7.setText(_translate("MainWindow", "Left part"))
        self.label_9.setText(_translate("MainWindow", "Big robot"))
        self.RB_Left_only.setText(_translate("MainWindow", "Left only"))
        self.label_23.setText(_translate("MainWindow", "Left part"))
        self.RB_Intermittent.setText(_translate("MainWindow", "Intermittent"))
        self.label_11.setText(_translate("MainWindow", "Right part"))
        self.label_22.setText(_translate("MainWindow", "Small robot"))
        self.label_3.setText(_translate("MainWindow", "Part processing time"))
        self.label_6.setText(_translate("MainWindow", "Number of parts processed"))
        self.label_10.setText(_translate("MainWindow", "Small robot"))
        self.PB_Pause_seq.setText(_translate("MainWindow", "Pause"))
        self.PB_Resume_seq.setText(_translate("MainWindow", "Resume"))
        self.label_8.setText(_translate("MainWindow", "Right part"))
        self.RB_Right_only.setText(_translate("MainWindow", "Right only"))
        self.RB_One_side.setText(_translate("MainWindow", "One side"))
        self.SR_Act_Stat.setText(_translate("MainWindow", "Active"))
        self.smallRobLPart7.setText(_translate("MainWindow", "8"))
        self.smallRobRPart6.setText(_translate("MainWindow", "7"))
        self.smallRobLPart8.setText(_translate("MainWindow", "9"))
        self.smallRobLPart0.setText(_translate("MainWindow", "1"))
        self.label_30.setText(_translate("MainWindow", "Grinding wheel deterioration status"))
        self.label_32.setText(_translate("MainWindow", "REPLACE"))
        self.label_31.setText(_translate("MainWindow", "GOOD"))
        self.smallRobRPart1.setText(_translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "Small robot"))
        self.smallRobLPart6.setText(_translate("MainWindow", "7"))
        self.smallRobLPart2.setText(_translate("MainWindow", "3"))
        self.smallRobRPart7.setText(_translate("MainWindow", "8"))
        self.smallRobRPart2.setText(_translate("MainWindow", "3"))
        self.smallRobRPart3.setText(_translate("MainWindow", "4"))
        self.SR_Pause_Stat.setText(_translate("MainWindow", "Paused"))
        self.smallRobLPart4.setText(_translate("MainWindow", "5"))
        self.smallRobRPart4.setText(_translate("MainWindow", "5"))
        self.smallRobRPart0.setText(_translate("MainWindow", "1"))
        self.smallRobLPart1.setText(_translate("MainWindow", "2"))
        self.smallRobLPart3.setText(_translate("MainWindow", "4"))
        self.label_35.setText(_translate("MainWindow", "Parts presence"))
        self.SR_Fault_Stat.setText(_translate("MainWindow", "Faulted"))
        self.smallRobRPart5.setText(_translate("MainWindow", "6"))
        self.smallRobRPart8.setText(_translate("MainWindow", "9"))
        self.smallRobLPart5.setText(_translate("MainWindow", "6"))
        self.label_13.setText(_translate("MainWindow", "Brush offset"))
        self.PB_SR_Off_UP.setText(_translate("MainWindow", "Up"))
        self.PB_SR_Off_DOWN.setText(_translate("MainWindow", "Down"))
        self.PB_Trig_Cam.setText(_translate("MainWindow", "Trigger camera"))
        self.PB_Reset_SR_Wheel.setText(_translate("MainWindow", "Reset wheel"))
        self.PB_Reset_LR_Wheel.setText(_translate("MainWindow", "Reset wheel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

    def runPolling(self):
        # Step 2: Create a QThread object
        self.thread = QThread()
        # Step 3: Create a worker object
        self.worker = Worker()
        # Step 4: Move worker to the thread
        self.worker.moveToThread(self.thread)
        # Step 5: Connect signals and slots
        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.worker.progress.connect(self.status_updates)
        # Step 6: Start the thread
        self.thread.start()

    def start_timer(self, name):
        self.tm_worker = WorkerThread()
        self.timer_thread_list.append((name, self.tm_worker))
        self.tm_worker.start()
        # set function to track progress in the thread
        if self.robot_side == "start_LRL":
            self.LRL_thread_id = self.tm_worker.currentThreadId()
            self.tm_worker.progress_tmr.connect(self.count_cycle_time_brl)
        elif self.robot_side == "start_LRR":
            self.LRR_thread_id = self.tm_worker.currentThreadId()
            self.tm_worker.progress_tmr.connect(self.count_cycle_time_brr)
        elif self.robot_side == "start_SRL":
            self.SRL_thread_id = self.tm_worker.currentThreadId()
            self.tm_worker.progress_tmr.connect(self.count_cycle_time_srl)
        elif self.robot_side == "start_SRR":
            self.SRR_thread_id = self.tm_worker.currentThreadId()
            self.tm_worker.progress_tmr.connect(self.count_cycle_time_srr)
        print(str(self.timer_thread_list))

    def stop_timer(self, name):
        # not yet finished the stop function
        for thread in self.timer_thread_list:
            if thread[0] == name:
                thread[1].stop_cnt()

    def count_cycle_time_brl(self, ms):
        self.LR_left_part_tmr.setText(str("%.2f" % ms))

    def count_cycle_time_brr(self, ms):
        self.LR_right_part_tmr.setText(str("%.2f" % ms))

    def count_cycle_time_srl(self, ms):
        self.SR_left_part_tmr.setText(str("%.2f" % ms))

    def count_cycle_time_srr(self, ms):
        self.SR_right_part_tmr.setText(str("%.2f" % ms))

    def encode(self, enc_msg):
        message = enc_msg.encode(FORMAT)
        msg_length = len(message)
        send_length = str(msg_length).encode(FORMAT)
        send_length += b' ' * (HEADER - len(send_length))
        # print(f"Encoded: {message}")
        message_return = (send_length, message)
        return message_return

    def send(self, msg):
        while True:
            message_enc = self.encode(msg)
            try:
                client.send(message_enc[0])
                client.send(message_enc[1])
                print(message_enc[1])
                break
            except:
                print(f"Exception captured")
                reconnect()

    def camera_trig_button(self):
        print("Camera triggered")
        self.send("HMI,cam,send_cam_data_HMI")

    def pause_seq(self):
        self.PAUSE = 1

    def resume_seq(self):
        self.PAUSE = 0

    def status_updates(self, incoming):
        recv = incoming
        print(f"from status update recv is {recv}")
        if len(recv) == 36:
            self.trig_camera(recv)
        if recv in ["start_LRR", "start_LRL", "start_SRR", "start_SRL"]:
            self.robot_side = recv
            self.start_timer(recv[5::])
        if recv in ["stop_LRR", "stop_LRL", "stop_SRR", "stop_SRL"]:
            self.stop_timer(recv[4::])
        if recv in self.error_samples:
            popup(text=self.error_samples[recv][0], title=self.error_samples[recv][1])
        if recv == "PICK_MODE":
            if self.RB_One_side.isChecked():
                self.side = "side_by_side"
            elif self.RB_Intermittent.isChecked():
                self.side = "intermittent"
            elif self.RB_Left_only.isChecked():
                self.side = "left_only"
            elif self.RB_Right_only.isChecked():
                self.side = "right_only"
            self.send(f"HMI,r1,{self.side}")
        if recv == "is_r1_paused":
            self.send(f"HMI,r1,{self.PAUSE}")
        if recv[0] == "q":
            if recv[1] == "b":
                if recv[2] == "l":
                    bl_prt_counter = int(self.LR_left_part_ctr.text())
                    bl_prt_counter += 1
                    self.LR_left_part_ctr.setText(f"{bl_prt_counter}")
                elif recv[2] == "r":
                    br_prt_counter = int(self.LR_right_part_ctr.text())
                    br_prt_counter += 1
                    self.LR_right_part_ctr.setText(f"{br_prt_counter}")
            elif recv[1] == "s":
                if recv[2] == "l":
                    sl_prt_counter = int(self.SR_left_part_ctr.text())
                    sl_prt_counter += 1
                    self.SR_left_part_ctr.setText(f"{sl_prt_counter}")
                elif recv[2] == "r":
                    sr_prt_counter = int(self.SR_right_part_ctr.text())
                    sr_prt_counter += 1
                    self.SR_right_part_ctr.setText(f"{sr_prt_counter}")
            self.display_sr_wheel_stat()
            self.display_lr_wheel_stat()
            self.write_to_file()
        # if recv[0] == "t":
        #     if recv[1] == "b":
        #         if recv[2] == "r":
        #             self.LR_left_part_tmr.setText(f"{recv[3::]}")
        #         elif recv[2] == "l":
        #             self.LR_right_part_tmr.setText(f"{recv[3::]}")
        #     elif recv[1] == "s":
        #         if recv[2] == "r":
        #             self.SR_left_part_tmr.setText(f"{recv[3::]}")
        #         elif recv[2] == "l":
        #             self.SR_right_part_tmr.setText(f"{recv[3::]}")
        if recv == "name":
            data = "HMI"
            self.send(f"{data}")
            print(f"Sent: {data}")
        if recv == "br_offset":
            self.send(f"HMI,r1,{self.BR_Offset}")
        elif recv == "sr_offset":
            self.send(f"HMI,r2,{self.SR_Offset}")
        if recv == "r2_active":
            self.SR_Act_Stat.setStyleSheet("background-color: green")
            self.SR_Pause_Stat.setStyleSheet("background-color: none")
            self.SR_Fault_Stat.setStyleSheet("background-color: none")
        elif recv == "r2_paused":
            self.SR_Act_Stat.setStyleSheet("background-color: none")
            self.SR_Pause_Stat.setStyleSheet("background-color: yellow")
            self.SR_Fault_Stat.setStyleSheet("background-color: none")
        elif recv == "r2_faulted":
            self.SR_Act_Stat.setStyleSheet("background-color: none")
            self.SR_Pause_Stat.setStyleSheet("background-color: none")
            self.SR_Fault_Stat.setStyleSheet("background-color: red")
        if recv == "r1_active":
            self.LR_Active_Stat.setStyleSheet("background-color: green")
            self.LR_Pause_Stat.setStyleSheet("background-color: none")
            self.LR_Fault_Stat.setStyleSheet("background-color: none")
        elif recv == "r1_paused":
            self.LR_Active_Stat.setStyleSheet("background-color: none")
            self.LR_Pause_Stat.setStyleSheet("background-color: yellow")
            self.LR_Fault_Stat.setStyleSheet("background-color: none")
        elif recv == "r1_faulted":
            self.LR_Active_Stat.setStyleSheet("background-color: none")
            self.LR_Pause_Stat.setStyleSheet("background-color: none")
            self.LR_Fault_Stat.setStyleSheet("background-color: red")

    def write_to_file(self):
        string = f'''Big robot right parts produced: {self.LR_left_part_ctr.text()} 
Big robot left parts produced: {self.LR_right_part_ctr.text()} 
Small robot right parts produced: {self.SR_left_part_ctr.text()} 
Small robot left parts produced: {self.SR_right_part_ctr.text()} '''
        with open("./logs.txt", "w") as f:
            f.write(string)

    def extra_offset_BR(self, dir):
        if 3.10 >= self.BR_Offset >= -3.10:
            self.BR_Offset += (0.1 * dir)
            if self.BR_Offset >= 3.10:
                self.BR_Offset = 3.00
            elif self.BR_Offset <= -3.10:
                self.BR_Offset = -3.00
        self.BR_Offset = float(str("%.2f" % self.BR_Offset))
        self.BR_Offset_Val.setText(str("%.2f" % self.BR_Offset))

    def extra_offset_SR(self, dir):
        if 3.10 >= self.SR_Offset >= -3.10:
            self.SR_Offset += (0.1 * dir)
            if self.SR_Offset >= 3.10:
                self.SR_Offset = 3.00
            elif self.SR_Offset <= -3.10:
                self.SR_Offset = -3.00
        self.SR_Offset = float(str("%.2f" % self.SR_Offset))
        self.SR_Offset_Val.setText(str("%.2f" % self.SR_Offset))

    def accumulated_part_count(self):
        today_time = QDateTime.currentDateTime()
        time_display = today_time.toString('yyyy-MM-dd hh:mm:ss dddd')
        with open("./logs.txt", "r") as f:
            read_data = f.read().strip("\n")
            text = read_data.split(" ")
        acc_quantity = int(text[5]) + int(text[11]) + int(text[17]) + int(text[23])
        write_str = time_display + " Total_parts: " + str(acc_quantity)
        print(write_str)
        with open("./daily_parts.txt", "a") as f:
            f.write(write_str)

    def read_from_file(self):
        try:
            with open("./logs.txt", "r") as f:
                read_data = f.read().strip("\n")
                text = read_data.split(" ")
            print(str(text))
            self.LR_right_part_ctr.setText(text[5])
            self.LR_left_part_ctr.setText(text[11])
            self.SR_right_part_ctr.setText(text[17])
            self.SR_left_part_ctr.setText(text[23])
        except:
            self.LR_right_part_ctr.setText("0")
            self.LR_left_part_ctr.setText("0")
            self.SR_right_part_ctr.setText("0")
            self.SR_left_part_ctr.setText("0")

    def trig_camera(self, cam_data):
        ctr1 = 0
        ctr2 = 0
        camera_data_list_sr = cam_data[0:18]
        camera_data_list_lr = cam_data[18::]
        print(f"small data: {camera_data_list_sr}, large data: {camera_data_list_lr}")
        for i in camera_data_list_sr:
            d = int(i)
            if d == 1:
                self.check_box_sr_list[ctr1].setChecked(True)
            else:
                self.check_box_sr_list[ctr1].setChecked(False)
            ctr1 += 1
        for i in camera_data_list_lr:
            d = int(i)
            if d == 1:
                self.check_box_lr_list[ctr2].setChecked(True)
            else:
                self.check_box_lr_list[ctr2].setChecked(False)
            ctr2 += 1

    def display_lr_wheel_stat(self):
        wheel_deterioration_lr_l = 100 - int(self.LR_left_part_ctr.text()) * 0.01
        wheel_deterioration_lr_r = 100 - int(self.LR_right_part_ctr.text()) * 0.01
        self.PrB_grWheel1LR.setValue(int(wheel_deterioration_lr_l))
        self.PrB_grWheel2LR.setValue(int(wheel_deterioration_lr_r))

    def display_sr_wheel_stat(self):
        wheel_deterioration_sr = 100 - (int(self.SR_right_part_ctr.text()) + int(self.SR_left_part_ctr.text())) * 0.02
        self.PrB_grWheelSR.setValue(int(wheel_deterioration_sr))

    def reset_grind_wheel_s(self):
        self.accumulated_part_count()
        self.PrB_grWheelSR.setValue(100)
        self.SR_left_part_ctr.setText("0")
        self.SR_right_part_ctr.setText("0")
        self.write_to_file()

    def reset_grind_wheel_l(self):
        self.accumulated_part_count()
        self.PrB_grWheel1LR.setValue(100)
        self.PrB_grWheel2LR.setValue(100)
        self.LR_left_part_ctr.setText("0")
        self.LR_right_part_ctr.setText("0")
        self.write_to_file()


stylesheet = '''QMainWindow {
        background-image: url("./logo.png");         
        background-position: center;} 
        QLabel { color : white; }
        QCheckBox { color : red; }
        QRadioButton { color : red; }
        QMessageBox { background-color: black; }'''

# if __name__ == "__main__":
app = QtWidgets.QApplication(sys.argv)
app.setStyleSheet(stylesheet)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
# t = QtCore.QTimer()
# t.singleShot(0, ui.runPolling)
# starting the app
sys.exit(app.exec_())
